# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
     matrix:
      dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/fhir-facade
    - name: Build
      run: dotnet build --no-restore
      working-directory: source/fhir-facade
    - name: Test
      run: dotnet test --no-build --verbosity normal -logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      working-directory: source/fhir-facade
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v4
      with:
       name: dotnet-results-${{ matrix.dotnet-version }}
       path: TestResults-${{ matrix.dotnet-version }}
       # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}   
